### ISSUE TITLE
when installed via snap, app seems to launch only the first time, but not on subsequent launches (20.04 ubuntu)

### ISSUE THREAD

**Issue by arooni** [anujdatar/onenote-desktop#20]
when i install the deb file, it loads again and again without issue.  

but when i load via snap, it seems to install once and then not again.

i am not sure that this is fundamental to your app (thank you for it btw) but rather, endemic to the way ubuntu handles snaps.  same thing has happened to me with authy but also other folks:

https://askubuntu.com/questions/1245108/some-snap-apps-dont-start-second-or-subsequent-time

**Comment by anujdatar** [comment]
Hmm. That should not be happening, it seemed to work fine during my testing. Do you get an error popup or does nothing happen?

Have you tried launching the app from terminal? If there are any errors you'll see them there. Open terminal and type `onenote-desktop`. If you do see any errors could you post them here?

**Comment by anujdatar** [comment]
Oh, seems to be an issue wit many snaps, I don't know why. I haven't personally run into it yet, but I'll do some digging.

What happens when you uninstall and reinstall the snap? Does it launch the first time, and then not again? Or does it not launch at all?

**Comment by anujdatar** [comment]
Can I ask which version of Ubuntu you are running? And what version of OneNote-desktop do you have installed? The previous version had a permissions issue on some systems. The latest version has a fix for that.

I just tested the latest snapstore version `1.3.2`, and my dev branch on `Ubuntu 20.04` and `Ubuntu 20.10` they seem to be working fine. I don't know exactly how to replicate the error at the moment, but I am looking into it. One of the threads mentioned that some people using ZFS had this issue with snaps, and some were electron based snaps. I will try a couple different VMs later today to see if I can replicate this.

I am actually in the process of pushing an update to the backend, it simplifies a part of the app. Don't know if it will fix the issue, but it is worth trying.

**Comment by arooni** [comment]
hihihihihi



may today be the best day of your life,
-------
david parkinson
founder - aroonilabs.com
blog - davidparkinson.com <https://www.davidparkinson.com/>
twitter - @followdavid <https://twitter.com/followdavid>


On Fri, Feb 5, 2021 at 8:13 AM Anuj Datar <notifications@github.com> wrote:

> Can I ask which version of Ubuntu you are running? And what version of
> OneNote-desktop do you have installed? The previous version had a
> permissions issue on some systems. The latest version has a fix for that.
>
20.04 and i believe your latest release 1.3.2 ; again on deb version it
works fine.

> I just tested the latest snapstore version 1.3.2, and my dev branch on Ubuntu
> 20.04 and Ubuntu 20.10 they seem to be working fine. I don't know exactly
> how to replicate the error at the moment, but I am looking into it. One of
> the threads mentioned that some people using ZFS had this issue with snaps,
> and some were electron based snaps. I will try a couple different VMs later
> today to see if I can replicate this.
>

i am running ext4 if that helps

> I am actually in the process of pushing an update to the backend, it
> simplifies a part of the app. Don't know if it will fix the issue, but it
> is worth trying.
>

many thanks for your quick responses!

**Comment by anujdatar** [comment]
>20.04 and i believe your latest release 1.3.2 ; again on deb version it
works fine.

Ya, Snaps have always had issues with a lot of apps..

**Comment by anujdatar** [comment]
Most issues should be fixed by the new release v2.0.0. Snaps should work too. Let me know if you are still using this app and run into errors. Feel free to reopen this issue if you run into problems
