### ISSUE TITLE
White window after changing notebook

### ISSUE THREAD

**Issue by a-Rahmati** [anujdatar/onenote-desktop#26]
Hello.

I was in a shared notebook. Then I switched to my own notebook. After that, the window got white and nothing happened. Closing and reopening the program doesn't help
![OneNote_001](https://user-images.githubusercontent.com/52320192/148682556-7a002a27-a6b8-4f4e-855e-d41c1b1f97fe.png)
I use Ubuntu 20.04 and installed onenote by snap.

**Comment by anujdatar** [comment]
Hi,
I think what might have happened is, during navigation between workbooks or when you closed one of the windows, the last notebook link in your local config got corrupted.

If you are using `.snap` or `onenote-desktop` from snapcraft
1. Close the app
2. Go to `~/snap/onenote-desktop/current/.config/OneNote/`
3. Delete the `config.json` file, just that file.
4. Restart the app. It should go back to the OneNote notebook selection screen

If you delete the whole folder from from step 2, the app will be fully reset, and you will need to re-login. Just deleting the json file is more like a soft-reset. It will leave mostly everything else as is and just send you back to notebook selection and resize the window.

**Comment by anujdatar** [comment]
should be fixed in v2.0.0.

1. There is a return to homepage button in the app menubar now.
2. There are app reset options too if you run into more issues
