### ISSUE TITLE
Keyboard input not worked

### ISSUE THREAD

**Issue by paxpia1** [anujdatar/onenote-desktop#30]
As I start onenote, I can't write fo Microsoft account input line.

**Comment by anujdatar** [comment]
Oh, there is no overlay in the app that should prevent you from accessing the OneNote or Microsoft's UI. I could use some more information about your situation:

1. Are you using the `deb`, `snap` or `AppImage` package?
2. Which flavor of Linux are you using? and your desktop environment?
3. Did you perform a fresh install or did you update from an older version?
4. I am assuming you must have tried a system restart. Can you access any other part of the app's UI? Can you use the Menubar at the top? If you can't see the Menubar at the top, try pressing the `Alt` key.
5. Maybe try an app reset? Soft reset first. If that doesn't work try a hard reset (this will wipe your local history and settings).
6. Is the About/Welcome window popup open on a separate screen? Close the popup and try using the app again. It is set to popup as a modal to explain some changes in the app. It opens when you initially start using the app. You can disable that popup during launch time. Maybe that is blocking keyboard/mouse input to the main app.

**Comment by paxpia1** [comment]
1. I installed it with snap
2. Ubuntu GNOMM
3. fresh install
4. No change with system restart. No problem with other UI. No problem from other menubar when mouse clicking
5. No change with soft reset and even with hard reset which means reinstall
6. 
7. I got success on another ubuntu machine with no problem.  It's very strange.
8. Please refer to the attached link[https://drive.google.com/file/d/1a2s5ystWpo3ezpnQAHKC8gMmxLCiWZDz/view?usp=sharing](url)

**Comment by anujdatar** [comment]
Hi, did you try installing the above packages? Did it do anything? Thanks

**Comment by anujdatar** [comment]
closing because of lack of information and is pretty stale
