### ISSUE TITLE
Windows app

### ISSUE THREAD

**Issue by xmha97** [anujdatar/onenote-desktop#37]
Please release an app for Windows.

**Comment by anujdatar** [comment]
Hey, Windows and MacOS already have native OneNote apps. You should be able to get them from the app store on either OS, or download from their official website. Plus they are built by Microsoft and don't depend on the web UI, unlike this app. I think you should see better performance on native apps. Official apps are supported on `Windows 7 and later`, and `MacOS Mojave and later`.

That being said, if you'd still like to test this app out on windows, you are welcome to try. Follow these steps:
1. Clone this git repo.
2. `cd` into directory
3. Run `npm install` to install all the packages and dependencies
4. Run `npm run tsc-start`

There is nothing Linux specific in this app, it's just that I didn't see the point of building binaries for Windows and MacOS.

**Comment by xmha97** [comment]
Yes, OneNote has an official application but I want to use two accounts on one PC. OneNote does not have this feature.
Also, if you build the Windows version of OneNote, I can make a portable version of it, which is good for me.
https://portableapps.com/development

**Comment by anujdatar** [comment]
Hmm.. I see. I'll look into it. Packaging for Windows, is not all that hard, but I'll have to look into how updates work. This is not something I can work on right away, but I'll try it out in a couple of weeks. I'll reopen the issue for now.

Until then you can use the steps I mentioned above. You will need NodeJs v16 installed to do that. You can get it from www.nodejs.org

**Comment by xmha97** [comment]
Thanks

**Comment by anujdatar** [comment]
closing. will not release a packaged app for windows. don't want to get into signing certificates. you can just clone the repo, install npm packages and run the app from cli or make a startup script.
