### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by DGuimaras** [anujdatar/onenote-desktop#38]
Hi,

Thanks for making oneNote available for Linux.

I can not find how to change the default font size for a entire notebook or section.  
Is it possible ?

Other thing that I miss from the Windows version of oneNote is the screenshot tool (it captures and pastes directly in the OneNote page). Do you have plans to include this feature?

**Comment by anujdatar** [comment]
Hi, I'll look into the default font size request.

The screenshot feature request might take a little longer. With work I have little time to devote to side projects like this. But I'll try to get it done soon. Thanks.

**Comment by anujdatar** [comment]
Font and other UI features are managed by the OneNote web app, so Microsoft. This app just serves the website in a desktop application wrapper. UI features isn't something I can add.
