### ISSUE TITLE
Unable to open notebooks from original MS OneNote using .one files

### ISSUE THREAD

**Issue by leofelipe222** [anujdatar/onenote-desktop#47]
When I try loading existing notebooks, using the regular .one files used to save documents on Windows, the app just ignores the command and goes back to its previous state and does not load the file.

I tried copying the files locally on my Ubuntu machine machine and over a network share from a Windows server.

Is that something you intend to add or fix?

**Comment by anujdatar** [comment]
Hi Leo,

I did not know you could export .one files on Windows, and import on another platform. I will have to look into it. Thanks for letting me know.

Anuj

**Comment by OSINTNewbie** [comment]
I believe I am having the same issue. I made a copy of an existing OneNote notebook and added to the Documents folder with my working notebooks created through Onenote-desktop. I can see the notebook but cannot open it. When I right-click the working notebooks I have the "Open" option. When I try the same thing on my notebook copied into the Documents folder I have a "Preview" option. When I try to Preview it tells me I need to download the notebook. I've downloaded a new copy, but the preview still doesn't work. Any help you can provide is greatly appreciated! Thanks!!

**Comment by anujdatar** [comment]
Hi, as far as I can tell, Microsoft's OneNote web app does not allow you to import or export `.one` files. Their native apps (Windows and maybe macOS) probably let you do that. I am just using Microsoft's application in a desktop wrapper. So I don't see a way around a limitation that they have intentionally set up.

I could be wrong, I probably need to look into this a little more. I'll try a few things and get back to you.

**Comment by leofelipe222** [comment]
Is MS OneNote available to use with Wine on Linux? If so, that could work, but I'm not sure.

**Comment by anujdatar** [comment]
Hmm, not that I know of. I think there are a few MS Office versions running on Wine out there in the wild. But the performance is degraded (afaik), and I don't know if anyone's tried OneNote separately.

**Comment by anujdatar** [comment]
Closing issue since OneNote web does not have note import and export capabilities. This is not something that I can control, it's all up to Microsoft to support this feature.
