### ISSUE TITLE
Sync status pop-up removes cursor

### ISSUE THREAD

**Issue by everybitmihaly** [anujdatar/onenote-desktop#53]
If using a slow internet connection, while typing, the sync status pop-up will come up in the right corner, removing the cursor from the page. If sync status notifications could be turned off, this would be a good fix for this problem. I use Ubuntu 22.04.

**Comment by anujdatar** [comment]
Hi, this app does not really control syncing with OneNote/OneDrive. It just serves the OneNote website in a desktop wrapper. Syncing is handled by Microsoft and their proprietary. I don't mess with that or inject anything.
