### ISSUE TITLE
can't open OneNote app after a couple of days installation

### ISSUE THREAD

**Issue by qingc2019** [anujdatar/onenote-desktop#54]
It happens 3 times since I installed a fresh Ubuntu 22.04 lately.  After (re)installing the OneNote, the app is launched, then, disappears.  Whatever clicking on the app, it doesn't do anything.

**Comment by anujdatar** [comment]
Hi, hope you were able to resolve the problem. I haven't seen this happen before. Not sure if you're still using the app. But let me know if you have some error logs for the issue. Have you tried launching the app from the terminal?

**Comment by qingc2019** [comment]
It works now after I re-installed it.
Thanks, Anuj!
