### ISSUE TITLE
Cannot access my notebooks

### ISSUE THREAD

**Issue by ksHamburg** [anujdatar/onenote-desktop#61]
Opening Onenote I get the following error message:

Sorry, we can't get your notebooks right now. Please try again later.
Reference number: 1cf98d50-5ce8-4d71-a292-23634bb5d0e7

Any ideas how to fix this issue?

**Comment by ksHamburg** [comment]
Hi Anuj,
thanks for responding so fast. Actually the problem did not resolve itself. But I realized, that this is rather a Microsoft issue than a problem with your fine app.
Best
Konrad

**Comment by anujdatar** [comment]
Oh, okay. Got it.
