### ISSUE TITLE
[Enhancement] Use GitHub Actions for CI/CD

### ISSUE THREAD

**Issue by zaxlofful** [anujdatar/onenote-desktop#68]
I saw a comment about how you have costs because of a CI and deployment, I wanted to recommend using GitHub actions to help with that. 

Actions are free and essentially give you a CI/CD pipeline for that project, you should be able to eliminate almost all of your costs; if not 100%.

**Comment by anujdatar** [comment]
I do use GitHub actions, just not on the repo I don't really use CI/CD for this repo. I think that's on my GitHub sponsors page, for my other container projects.

**Comment by zaxlofful** [comment]
You don't use GitHub actions for those other projects?
