### ISSUE TITLE
Electron-store EPERM-chown error in strict confinement snap

### ISSUE THREAD

**Issue by anujdatar** [anujdatar/onenote-desktop#7]
Electron-store does not have access to local snap config files when when snap is build using '**strict**' confinement. Event calling the ElectronStore.set function give the following error:

**A JavaScript error occurred in the main process**

Uncaught Exception:
Error: EPERM: operation not permitted, chown '/home/anuj/snap/onenote-desktop/x1/.config/OneNote/config.json.1014786569'
- at Object.chownSync (fs.js:1142:3)
- at Function.writeFileSync [as sync] (/snap/onenote-desktop/x1/resources/app.asar/node_modules/write-file-atomic/index.js:196:27)
- at ElectronStore.set store [as store] (/snap/onenote-desktop/x1/resources/app.asar/node_modules/conf/index.js:227:19)
- at ElectronStore.set store (/snap/onenote-desktop/x1/resources/app.asar/node_modules/conf/index.js:152:14)
- at BrowseWindow.<anonymous> (/snap/onenote-desktop/x1/resources/app.asar/src/main.js:44:10)
 - at BrowserWindow.emit (events.js:194:13)

Error not seen if confinement set to '**devmode**' or '**classic**'. when the snap environment has access to home directory

**Comment by develar** [comment]
Please use `SNAP_USER_DATA` env var. I mean — if such env is defined, then you must use it to store user configs.

**Comment by develar** [comment]
I filed https://github.com/sindresorhus/electron-store/issues/75, please vote or even send PR ;)

**Comment by anujdatar** [comment]
I just ran the snap in shell to get env variables

```bash
$ snap run --shell onenote-desktop

$ env | grep SNAP
SNAP_DESKTOP_RUNTIME=/snap/onenote-desktop/x1/gnome-platform
**SNAP_USER_DATA=/home/anuj/snap/onenote-desktop/x1**
SNAP_REVISION=x1
SNAP_ARCH=amd64
SNAP_INSTANCE_KEY=
SNAP_USER_COMMON=/home/anuj/snap/onenote-desktop/common
SNAP=/snap/onenote-desktop/x1
SNAP_COMMON=/var/snap/onenote-desktop/common
SNAP_NAME=onenote-desktop
SNAP_INSTANCE_NAME=onenote-desktop
SNAP_DATA=/var/snap/onenote-desktop/x1
SNAP_COOKIE=7xnvN4GXLY6SlqgLcVrqg3RTxj0K0MxGshCQNb9HB043
SNAP_REEXEC=
SNAP_CONTEXT=7xnvN4GXLY6SlqgLcVrqg3RTxj0K0MxGshCQNb9HB043
SNAP_VERSION=1.1.2
SNAP_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void
```

`electron-store` is trying to access the same folder as `SNAP_USER_DATA`. And, `electron-builder` uses the `home` plug by default. Plus the Snap works perfectly fine in `devmode` or `classic` confinement.

I apologize if I didn't understand your comment completely. I just started experimenting with snaps and snapcraft yesterday. Do I have to add `SNAP_USER_DATA` to env vars somewhere else in the app or build process?

**Comment by develar** [comment]
@anujdatar It will be fixed today (https://github.com/electron-userland/electron-builder/issues/4038).

**Comment by anujdatar** [comment]
Thanks for the quick replies. I really appreciate it.

**Comment by anujdatar** [comment]
Aah, okay. that makes sense. I did try electron-store 4 first, then configstore 5. They both have the same chown problem in snap. Thanks

**Comment by anujdatar** [comment]
Yeah, it's apparently, there's no way to turn off chown in write-file-atomic or something. which causes configstore 5 and electron-store(conf) 4 to not work with Snap. Thanks for your replies. I'll try configstore 4.

**Comment by brunolemos** [comment]
Maybe this should be reopened since the fix didn't land yet. Still getting this crash with snap.

**Comment by anujdatar** [comment]
Hi Bruno,
The issue actually exists with [`write-file-atomic`](https://github.com/npm/write-file-atomic), which tries to change ownership. One of my dependencies used that. I have since written a simple package that uses plain `fs.writeFile` instead of `atomic-file-write`, and I use that if when I need to use snaps.

Since the core issue is not in repo anyway, I don't think it should be open here. I believe these issues are open in my old dependency and [`write-file-atomic`](https://github.com/npm/write-file-atomic/issues/50).
