### ISSUE TITLE
ln: failed to create symbolic link '/home/zangetsu/snap/onenote-desktop/20/.config/dconf/user': File exists

### ISSUE THREAD

**Issue by archenroot** [anujdatar/onenote-desktop#70]
![image](https://github.com/anujdatar/onenote-desktop/assets/553512/d1808a29-b3d7-4021-9037-9f239723bf40)

**Comment by anujdatar** [comment]
Was the app working before and did this just start happening? Or did it happen on first launch?

I would try to delete that file and relaunch the app. `/home/zangetsu/snap/onenote-desktop/20/.config/dconf/user`

Let me know if this works.

Anuj

**Comment by archenroot** [comment]
Yeah, the application worked before, after reboot above error message appeared, I deleted the file and app just works again.

**Comment by anujdatar** [comment]
oh, okay. not sure why that would have happened. maybe something got corrupted. but i'm glad you got it working again.
